# Site settings
title: Agustín Moracho
email: agustinmoracho@example.com
description: > # this means to ignore newlines until "baseurl:"
  Soluciones de aislamineto e impermeabilizaciones.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Agustín Moracho
email: info@agustinmoracho.com
facebook_username:
google_username: 115885911036446905407
address:
  - line: Baratxategi 46, 2 Izda.
  - line: 20015 - San Sebastián
  # Feel free to add more lines here 
telephone_1: 943 246 765
telephone_2: 645 710 290
copyright: Agustín Moracho

# API settings
google_api_key: AIzaSyCQol0dydPAKowVxVW5jtY9CzmpjRSOOdE 
map_address: Baratxategi 46, San Sebastián

# Build settings
markdown: kramdown
